debug: false
game-config-mode: "scheduler"
language: "en-US"
spawnpoint:
  enable: false
  x: 0
  y: 64
  z: 0
database:
  enabled: true
  host: "127.0.0.1"
  port: 5432
  database: "gamevoting"
  username: "minigames"
  password: ""
holograms:
  locations: []
