name: GameVoting
version: '1.1.2'
main: com.talexck.gameVoting.GameVoting
api-version: '1.16'
depend: [CloudNet-Bridge]
softdepend: [DecentHolograms]

commands:
  vote:
    description: Open voting interface or manage voting sessions
    usage: /<command> [start|stop|forcestart|ready|gamestart|holograms|session|reload|join]
    permission: gamevoting.vote
    permission-message: "&cYou don't have permission to use this command"
  party:
    description: Party management commands
    usage: /<command> [create|invite|accept|decline|exit|list|transfer|vote|forcestart]
    aliases: [p]
    permission: gamevoting.party
    permission-message: "&cYou don't have permission to use this command"

permissions:
  gamevoting.vote:
    description: Open voting menu
    default: true
  gamevoting.vote.admin:
    description: Start and stop voting sessions
    default: op
  gamevoting.party:
    description: Use party system
    default: true
  gamevoting.party.leader:
    description: Party leader privileges (voting, force start)
    default: true
